#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 18 19:53:18 2022

@author: maramarsu

Code is from video on youtube:
https://www.youtube.com/watch?v=myFD0np9eys&t=6
"""

import pandas as pd
import numpy as np
import yfinance as yf
import datetime as dt
from pandas_datareader import data as  pdr

yf.pdr_override()
stock = "BTC-USD"
#print(stock)

startyear=2017
startmonth=1
startday=1

start=dt.datetime(startyear,startmonth,startday)

now=dt.datetime.now()

df=pdr.get_data_yahoo(stock,start,now)

#print(df)

ma=50 #moving average
smaString="Sma_"+str(ma)
df[smaString]=df.iloc[:,4].rolling(window=ma).mean()
#print(df)
df=df.iloc[ma:] #removes 50 first rows, MA=50 
print(df)

for i in df.index:
    print(df[smaString][i])
"""
for i in df.index:
    #print(df.iloc[:,4][i])
    #print(df["Adj Close"][i]) - This also works
    print(df[smaString][1])
"""